version: "3.8"

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: tingeso
      MYSQL_USER: kartadmin
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-net

  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    image: matiassandovalp/backend:latest
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/tingeso?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: kartadmin
      SPRING_DATASOURCE_PASSWORD: 1234
      
    ports:
      - "8090:8090"
    networks:
      - app-net

  frontend:
    build:
      context: ./Frontend/kartingrm-frontend
      dockerfile: Dockerfile
    image: tuusuario/frontend:latest
    ports:
      - "3000:80"
    networks:
      - app-net

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-net

volumes:
  db_data:

networks:
  app-net:
    driver: bridge